set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

#####            create clock         #####
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports clk_50MHz]
create_clock -period 20.000 -name sys_clk_pin -add [get_ports clk_50MHz]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TCK_IBUF]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TCK_IBUF_BUFG]

#####            rst define           #####
set_property PACKAGE_PIN N15 [get_ports ext_reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_n]


#####            UART I/O             #####
set_property PACKAGE_PIN D19 [get_ports UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]
set_property PACKAGE_PIN D20 [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]

#####                spi define               #####
set_property PACKAGE_PIN E19 [get_ports {SPI_0_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_0_ss_io[0]}]
set_property PACKAGE_PIN E18 [get_ports SPI_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_sck_io]
set_property PACKAGE_PIN G18 [get_ports SPI_0_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io3_io]
set_property PACKAGE_PIN G17 [get_ports SPI_0_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io2_io]
set_property PACKAGE_PIN H17 [get_ports SPI_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io1_io]
set_property PACKAGE_PIN H16 [get_ports SPI_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io0_io]

#####               MCU JTAG define           #####
set_property PACKAGE_PIN K14 [get_ports TDO]
set_property IOSTANDARD LVCMOS33 [get_ports TDO]
set_property PACKAGE_PIN J14 [get_ports TCK]
set_property IOSTANDARD LVCMOS33 [get_ports TCK]
set_property PACKAGE_PIN H15 [get_ports TDI]
set_property IOSTANDARD LVCMOS33 [get_ports TDI]
set_property PACKAGE_PIN G15 [get_ports TMS]
set_property IOSTANDARD LVCMOS33 [get_ports TMS]

#####                PMU define               #####
#set_property PACKAGE_PIN M18 [get_ports pmu_paden]
#set_property IOSTANDARD LVCMOS33 [get_ports pmu_paden]
#set_property PACKAGE_PIN M17 [get_ports pmu_padrst]
#set_property IOSTANDARD LVCMOS33 [get_ports pmu_padrst]
#set_property PACKAGE_PIN D20 [get_ports mcu_wakeup]
#set_property IOSTANDARD LVCMOS33 [get_ports mcu_wakeup]

#####                gpio define              #####
set_property PACKAGE_PIN F17 [get_ports {gpio_tri_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[31]}]
set_property PACKAGE_PIN F16 [get_ports {gpio_tri_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[30]}]
set_property PACKAGE_PIN F20 [get_ports {gpio_tri_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[29]}]
set_property PACKAGE_PIN F19 [get_ports {gpio_tri_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[28]}]
set_property PACKAGE_PIN G20 [get_ports {gpio_tri_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[27]}]
set_property PACKAGE_PIN G19 [get_ports {gpio_tri_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[26]}]
set_property PACKAGE_PIN H18 [get_ports {gpio_tri_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[25]}]
set_property PACKAGE_PIN J18 [get_ports {gpio_tri_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[24]}]
set_property PACKAGE_PIN L20 [get_ports {gpio_tri_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[23]}]
set_property PACKAGE_PIN L19 [get_ports {gpio_tri_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[22]}]
set_property PACKAGE_PIN M20 [get_ports {gpio_tri_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[21]}]
set_property PACKAGE_PIN M19 [get_ports {gpio_tri_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[20]}]
set_property PACKAGE_PIN K18 [get_ports {gpio_tri_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[19]}]
set_property PACKAGE_PIN K17 [get_ports {gpio_tri_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[18]}]
set_property PACKAGE_PIN J19 [get_ports {gpio_tri_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[17]}]
set_property PACKAGE_PIN K19 [get_ports {gpio_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[16]}]
set_property PACKAGE_PIN H20 [get_ports {gpio_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[15]}]
set_property PACKAGE_PIN J20 [get_ports {gpio_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[14]}]
set_property PACKAGE_PIN L17 [get_ports {gpio_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[13]}]
set_property PACKAGE_PIN L16 [get_ports {gpio_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[12]}]
set_property PACKAGE_PIN W19 [get_ports {gpio_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[11]}]
set_property PACKAGE_PIN W18 [get_ports {gpio_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[10]}]
set_property PACKAGE_PIN R14 [get_ports {gpio_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[9]}]
set_property PACKAGE_PIN P14 [get_ports {gpio_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[8]}]
set_property PACKAGE_PIN Y17 [get_ports {gpio_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[7]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[6]}]
set_property PACKAGE_PIN W15 [get_ports {gpio_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[5]}]
set_property PACKAGE_PIN V15 [get_ports {gpio_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[4]}]
# KEY2
set_property PACKAGE_PIN N16 [get_ports {gpio_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[3]}]
# KEY3
set_property PACKAGE_PIN T17 [get_ports {gpio_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[2]}]
# LED1
set_property PACKAGE_PIN M14 [get_ports {gpio_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[1]}]
# LED2
set_property PACKAGE_PIN M15 [get_ports {gpio_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_tri_io[0]}]


#####         SPI Configurate Setting        #######
# set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
# set_property CONFIG_MODE SPIx4 [current_design]
# set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

